##### ketan nikam
##### 126M1B011
# Experiment 1: Tokenization, Stemming and Lemmatization
##### NLP Lab – PCCoE M.Tech

## 1. Import Libraries and Load spaCy

In [3]:
import spacy
import nltk
import pandas as pd
from nltk.stem import PorterStemmer, SnowballStemmer

print("spaCy version:", spacy.__version__)
print("NLTK version:", nltk.__version__)

nlp = spacy.load("en_core_web_sm")
print("spaCy English model loaded successfully.")

spaCy version: 3.8.4
NLTK version: 3.10.3
spaCy English model loaded successfully.

## 2. Step 1 – Enter the Given Text

In [44]:
text =  """
The children are playing in the gardens while their parents watch them.
A researcher studies language patterns and analyzes different documents.
The students were writing, reading, and discussing their experiments.
The machines process data, processed old records, and are processing new files.
Good preprocessing techniques help computers understand words and meanings.
""".strip()

print(text)
print("\nCharacter count:", len(text))

The children are playing in the gardens while their parents watch them.
A researcher studies language patterns and analyzes different documents.
The students were writing, reading, and discussing their experiments.
The machines process data, processed old records, and are processing new files.
Good preprocessing techniques help computers understand words and meanings.

Character count: 370

## Step 2 – Create the spaCy Document

In [45]:
doc = nlp(text)

print("Number of spaCy tokens:", len(doc))

print("First 30 spaCy tokens: -   ")

print([token.text for token in doc[:30]])

Number of spaCy tokens: 64
First 30 spaCy tokens: -
['The', 'children', 'are', 'playing', 'in', 'the', 'gardens', 'while', 'their', 'parents', 'watch', 'them', '.', '\n', 'A', 'researcher', 'studies', 'language', 'patterns', 'and', 'analyzes', 'different', 'documents', '.', '\n', 'The', 'students', 'were', 'writing', ',']

## 3.Perform Different Tokenization Methods

### 3.1 Whitespace Tokenization
Whitespace tokenization simply splits the text wherever whitespace occurs. Therefore, punctuation may remain attached to words such as language.

In [46]:
whitespace_tokens = text.split()

print("Whitespace tokens:")
print(whitespace_tokens )

print("\nCount:", len(whitespace_tokens))

Whitespace tokens:
['The', 'children', 'are', 'playing', 'in', 'the', 'gardens', 'while', 'their', 'parents', 'watch', 'them.', 'A', 'researcher', 'studies', 'language', 'patterns', 'and', 'analyzes', 'different', 'documents.', 'The', 'students', 'were', 'writing,', 'reading,', 'and', 'discussing', 'their', 'experiments.', 'The', 'machines', 'process', 'data,', 'processed', 'old', 'records,', 'and', 'are', 'processing', 'new', 'files.', 'Good', 'preprocessing', 'techniques', 'help', 'computers', 'understand', 'words', 'and', 'meanings.']

Count: 51

### 3.2 spaCy Word Tokenization
spaCy uses linguistic tokenization rules and separates punctuation from words.

In [47]:
spacy_tokens = [token.text for token in doc]

print("spaCy tokens:")
print(spacy_tokens)

print("\nCount:", len(spacy_tokens))

spaCy tokens:
['The', 'children', 'are', 'playing', 'in', 'the', 'gardens', 'while', 'their', 'parents', 'watch', 'them', '.', '\n', 'A', 'researcher', 'studies', 'language', 'patterns', 'and', 'analyzes', 'different', 'documents', '.', '\n', 'The', 'students', 'were', 'writing', ',', 'reading', ',', 'and', 'discussing', 'their', 'experiments', '.', '\n', 'The', 'machines', 'process', 'data', ',', 'processed', 'old', 'records', ',', 'and', 'are', 'processing', 'new', 'files', '.', '\n', 'Good', 'preprocessing', 'techniques', 'help', 'computers', 'understand', 'words', 'and', 'meanings', '.']

Count: 64

### 3.2 spaCy Tokens Without Punctuation and Spaces
This filtered list is used for stemming, lemmatization, and vocabulary analysis.

In [48]:
filtered_doc_tokens = [
    token for token in doc
    if not token.is_space and not token.is_punct
]

clean_tokens = [token.text for token in filtered_doc_tokens]

print("Before filtering:", len(spacy_tokens))
print("After filtering: ", len(clean_tokens))
print("Removed:         ", len(spacy_tokens) - len(clean_tokens))

print("\nFiltered tokens:")
print(clean_tokens)

Before filtering: 64
After filtering:  51
Removed:          13

Filtered tokens:
['The', 'children', 'are', 'playing', 'in', 'the', 'gardens', 'while', 'their', 'parents', 'watch', 'them', 'A', 'researcher', 'studies', 'language', 'patterns', 'and', 'analyzes', 'different', 'documents', 'The', 'students', 'were', 'writing', 'reading', 'and', 'discussing', 'their', 'experiments', 'The', 'machines', 'process', 'data', 'processed', 'old', 'records', 'and', 'are', 'processing', 'new', 'files', 'Good', 'preprocessing', 'techniques', 'help', 'computers', 'understand', 'words', 'and', 'meanings']

## 4. Tokenization Comparison

In [49]:
tokenization_summary = pd.DataFrame({
    "Method": [
        "Whitespace tokenization",
        "spaCy tokenization",
        "spaCy filtered tokenization"
    ],
    "Token Count": [
        len(whitespace_tokens),
        len(spacy_tokens),
        len(clean_tokens)
    ]
})

display(tokenization_summary)

                        Method  Token Count
0      Whitespace tokenization           51
1           spaCy tokenization           64
2  spaCy filtered tokenization           51

## 5. Stemming
Stemming applies heuristic rules and may produce a string that is not a valid English word. The lab manual specifically asks for both PorterStemmer and SnowballStemmer.

### 5.1 PorterStemmer

In [50]:
porter = PorterStemmer()

original_words = [
    token.text.lower()
    for token in filtered_doc_tokens
    if token.is_alpha
]

porter_stems = [porter.stem(word) for word in original_words]

print("Porter stems:")
print(porter_stems)

Porter stems:
['the', 'children', 'are', 'play', 'in', 'the', 'garden', 'while', 'their', 'parent', 'watch', 'them', 'a', 'research', 'studi', 'languag', 'pattern', 'and', 'analyz', 'differ', 'document', 'the', 'student', 'were', 'write', 'read', 'and', 'discuss', 'their', 'experi', 'the', 'machin', 'process', 'data', 'process', 'old', 'record', 'and', 'are', 'process', 'new', 'file', 'good', 'preprocess', 'techniqu', 'help', 'comput', 'understand', 'word', 'and', 'mean']

### 5.2 SnowballStemmer

In [51]:
snowball = SnowballStemmer("english")

original_words = [
    token.text.lower()
    for token in filtered_doc_tokens
    if token.is_alpha
]

snowball_stems = [snowball.stem(word) for word in original_words]


print("\nSnowball stems:")
print(snowball_stems)

Snowball stems:
['the', 'children', 'are', 'play', 'in', 'the', 'garden', 'while', 'their', 'parent', 'watch', 'them', 'a', 'research', 'studi', 'languag', 'pattern', 'and', 'analyz', 'differ', 'document', 'the', 'student', 'were', 'write', 'read', 'and', 'discuss', 'their', 'experi', 'the', 'machin', 'process', 'data', 'process', 'old', 'record', 'and', 'are', 'process', 'new', 'file', 'good', 'preprocess', 'techniqu', 'help', 'comput', 'understand', 'word', 'and', 'mean']

### 5.3 Porter vs Snowball – Different Outputs
This cell identifies words for which the two stemmers produce different stems.

In [52]:
stemmer_differences = pd.DataFrame([
    {
        "Word": word,
        "Porter": porter.stem(word),
        "Snowball": snowball.stem(word)
    }
    for word in original_words
    if porter.stem(word) != snowball.stem(word)
])

if stemmer_differences.empty:
    print("No Porter/Snowball differences found for this text.")
else:
    display(stemmer_differences.drop_duplicates().reset_index(drop=True))

No Porter/Snowball differences found for this text.

## 6.  Lemmatization Using spaCy
Lemmatization maps words to their dictionary/base forms using linguistic information. spaCy's model also provides POS information, which helps explain why lemmatization is generally more interpretable than heuristic stemming.

In [53]:
lemmas = [
    token.lemma_.lower()
    for token in filtered_doc_tokens
    if token.is_alpha
]

print("spaCy lemmas:")
print(lemmas)

spaCy lemmas:
['the', 'child', 'be', 'play', 'in', 'the', 'garden', 'while', 'their', 'parent', 'watch', 'they', 'a', 'researcher', 'study', 'language', 'pattern', 'and', 'analyze', 'different', 'document', 'the', 'student', 'be', 'write', 'read', 'and', 'discuss', 'their', 'experiment', 'the', 'machine', 'process', 'datum', 'process', 'old', 'record', 'and', 'be', 'process', 'new', 'file', 'good', 'preprocessing', 'technique', 'help', 'computer', 'understand', 'word', 'and', 'meaning']

## 7. POS, Stem and Lemma Inspection
The lab manual recommends inspecting POS and lemmas together to understand the linguistic difference between stemming and lemmatization.

In [55]:
word_analysis = pd.DataFrame({
    "Original": [token.text for token in filtered_doc_tokens if token.is_alpha],
    "POS": [token.pos_ for token in filtered_doc_tokens if token.is_alpha],
    "Porter Stem": [porter.stem(token.text.lower())
                    for token in filtered_doc_tokens if token.is_alpha],
    "Snowball Stem": [snowball.stem(token.text.lower())
                      for token in filtered_doc_tokens if token.is_alpha],
    "spaCy Lemma": [token.lemma_.lower()
                    for token in filtered_doc_tokens if token.is_alpha]
})

display(word_analysis)

         Original    POS Porter Stem Snowball Stem    spaCy Lemma
0             The    DET         the           the            the
1        children   NOUN    children      children          child
2             are    AUX         are           are             be
3         playing   VERB        play          play           play
4              in    ADP          in            in             in
5             the    DET         the           the            the
6         gardens   NOUN      garden        garden         garden
7           while  SCONJ       while         while          while
8           their   PRON       their         their          their
9         parents   NOUN      parent        parent         parent
10          watch   VERB       watch         watch          watch
11           them   PRON        them          them           they
12              A    DET           a             a              a
13     researcher   NOUN    research      research     researcher
14        studies   NOUN       studi         studi          study
15       language   NOUN     languag       languag       language
16       patterns   NOUN     pattern       pattern        pattern
17            and  CCONJ         and           and            and
18       analyzes   VERB      analyz        analyz        analyze
19      different    ADJ      differ        differ      different
20      documents   NOUN    document      document       document
21            The    DET         the           the            the
22       students   NOUN     student       student        student
23           were    AUX        were          were             be
24        writing   VERB       write         write          write
25        reading   VERB        read          read           read
26            and  CCONJ         and           and            and
27     discussing   VERB     discuss       discuss        discuss
28          their   PRON       their         their          their
29    experiments   NOUN      experi        experi     experiment
30            The    DET         the           the            the
31       machines   NOUN      machin        machin        machine
32        process   NOUN     process       process        process
33           data   NOUN        data          data          datum
34      processed   VERB     process       process        process
35            old    ADJ         old           old            old
36        records   NOUN      record        record         record
37            and  CCONJ         and           and            and
38            are    AUX         are           are             be
39     processing   VERB     process       process        process
40            new    ADJ         new           new            new
41          files   NOUN        file          file           file
42           Good    ADJ        good          good           good
43  preprocessing   NOUN  preprocess    preprocess  preprocessing
44     techniques   NOUN    techniqu      techniqu      technique
45           help   VERB        help          help           help
46      computers   NOUN      comput        comput       computer
47     understand   VERB  understand    understand     understand
48          words   NOUN        word          word           word
49            and  CCONJ         and           and            and
50       meanings   NOUN        mean          mean        meaning

## 8. Comparison Table for Selected Words
These examples follow the lab manual's expected observations: **studying, studied, processing**, and **systems**.

In [57]:
selected_words = [
    "writing",
    "processed",
    "discussing",
    "computers"
]

selected_rows = []

for word in selected_words:
    matches = [
        token for token in filtered_doc_tokens
        if token.is_alpha and token.text.lower() == word
    ]

    if matches:
        token = matches[0]
        selected_rows.append({
            "Original": token.text,
            "POS": token.pos_,
            "Porter Stem": porter.stem(word),
            "Snowball Stem": snowball.stem(word),
            "spaCy Lemma": token.lemma_.lower()
        })

selected_comparison = pd.DataFrame(selected_rows)
display(selected_comparison)

     Original   POS Porter Stem Snowball Stem spaCy Lemma
0     writing  VERB       write         write       write
1   processed  VERB     process       process     process
2  discussing  VERB     discuss       discuss     discuss
3   computers  NOUN      comput        comput    computer

## 9. Compare Word Variations
A lower number of unique normalized forms indicates stronger vocabulary reduction, but it does not automatically mean better preprocessing. The normalized forms must also remain meaningful.

For stemming and lemmatization, the reduction percentage is calculated using the formula from the lab manual:

Reduction % = (1 - normalized unique forms / original unique forms) × 100

In [58]:
def reduction_percentage(original, normalized):
    original_unique = len(set(original))
    normalized_unique = len(set(normalized))

    if original_unique == 0:
        return 0.0

    return (1 - normalized_unique / original_unique) * 100

porter_reduction = reduction_percentage(original_words, porter_stems)
snowball_reduction = reduction_percentage(original_words, snowball_stems)
lemma_reduction = reduction_percentage(original_words, lemmas)

variation_metrics = pd.DataFrame({
    "Method": [
        "Original words",
        "Porter stemming",
        "Snowball stemming",
        "spaCy lemmatization"
    ],
    "Total Words": [
        len(original_words),
        len(porter_stems),
        len(snowball_stems),
        len(lemmas)
    ],
    "Unique Forms": [
        len(set(original_words)),
        len(set(porter_stems)),
        len(set(snowball_stems)),
        len(set(lemmas))
    ],
    "Reduction %": [
        0.0,
        round(porter_reduction, 2),
        round(snowball_reduction, 2),
        round(lemma_reduction, 2)
    ]
})

display(variation_metrics)

                Method  Total Words  Unique Forms  Reduction %
0       Original words           51            43         0.00
1      Porter stemming           51            41         4.65
2    Snowball stemming           51            41         4.65
3  spaCy lemmatization           51            40         6.98

## 10. Tokenization/Stemming/Lemmatization Result Table
The lab manual's result table asks for total tokens/words, unique forms, reduction percentage, and semantic coherence.

For tokenization, reduction percentage is not a meaningful normalization measure because tokenization changes token boundaries rather than normalizing word forms. Therefore, it is reported as N/A instead of inventing a misleading value.

In [62]:
result_table = pd.DataFrame({
    "Method": [
        "Whitespace tokenization",
        "spaCy tokenization",
        "Porter stemming",
        "Snowball stemming",
        "spaCy lemmatization"
    ],
    "Total Tokens/Words": [
        len(whitespace_tokens),
        len(spacy_tokens),
        len(porter_stems),
        len(snowball_stems),
        len(lemmas)
    ],
    "Unique Forms": [
        len(set(whitespace_tokens)),
        len(set(spacy_tokens)),
        len(set(porter_stems)),
        len(set(snowball_stems)),
        len(set(lemmas))
    ],
    "Reduction %": [
        "N/A",
        "N/A",
        round(porter_reduction, 2),
        round(snowball_reduction, 2),
        round(lemma_reduction, 2)
    ],
    "Semantic Coherence": [
        "Not applicable",
        "Not applicable",
        "Lower – stems may be truncated/non-words",
        "Lower – stems may be truncated/non-words",
        "Higher – generally interpretable base forms"
    ]
})

display(result_table)

,Method,Total Tokens/Words,Unique Forms,Reduction %,Semantic Coherence
0,Whitespace tokenization,51,44,N/A,Not applicable
1,spaCy tokenization,64,47,N/A,Not applicable
2,Porter stemming,51,41,4.65,Lower – stems may be truncated/non-words
3,Snowball stemming,51,41,4.65,Lower – stems may be truncated/non-words
4,spaCy lemmatization,51,40,6.98,Higher – generally interpretable base forms

## 11. Qualitative Semantic Coherence
The lab manual asks us to evaluate semantic coherence qualitatively. We check whether:

normalized forms are valid/interpretable English words,
related forms such as study, studying, and studied are reasonably normalized,
stems look unnatural or truncated,
lemmas preserve recognizable base forms.
A vocabulary reduction percentage alone is not sufficient to claim semantic superiority.

In [65]:
# Representative examples for qualitative observation

examples = ["writing", "processing", "discussing", "computers"]

observation_rows = []

for word in examples:
    token = next(
        (t for t in filtered_doc_tokens
         if t.is_alpha and t.text.lower() == word),
        None
    )

    if token is not None:
        observation_rows.append({
            "Original": word,
            "Porter Stem": porter.stem(word),
            "Snowball Stem": snowball.stem(word),
            "spaCy Lemma": token.lemma_.lower(),
            "Observation": (
                "Lemma is a recognizable base word; stems may be truncated."
                if word in {"studying", "studied"}
                else
                "Normalization produces an interpretable form."
                if word == "processing"
                else
                "Plural normalization is clear."
            )
        })

observation_df = pd.DataFrame(observation_rows)
display(observation_df)

,Original,Porter Stem,Snowball Stem,spaCy Lemma,Observation
0,writing,write,write,write,Plural normalization is clear.
1,processing,process,process,process,Normalization produces an interpretable form.
2,discussing,discuss,discuss,discuss,Plural normalization is clear.
3,computers,comput,comput,computer,Plural normalization is clear.

## 12. Sentence-Level Comparison
The lab manual uses this short sentence to demonstrate the difference between stemming and lemmatization.

In [67]:
sample = "The children are playing in the gardens while their parents watch them."
sample_doc = nlp(sample)

sample_words = [token for token in sample_doc if token.is_alpha]

sample_porter = [porter.stem(token.text.lower()) for token in sample_words]
sample_snowball = [snowball.stem(token.text.lower()) for token in sample_words]
sample_lemmas = [token.lemma_.lower() for token in sample_words]

print("Original:")
print(sample)

print("\nPorter stems:")
print(sample_porter)

print("\nSnowball stems:")
print(sample_snowball)

print("\nspaCy lemmas:")
print(sample_lemmas)

Original:
The children are playing in the gardens while their parents watch them.

Porter stems:
['the', 'children', 'are', 'play', 'in', 'the', 'garden', 'while', 'their', 'parent', 'watch', 'them']

Snowball stems:
['the', 'children', 'are', 'play', 'in', 'the', 'garden', 'while', 'their', 'parent', 'watch', 'them']

spaCy lemmas:
['the', 'child', 'be', 'play', 'in', 'the', 'garden', 'while', 'their', 'parent', 'watch', 'they']

## 13. Final Summary
This summary is generated directly from the experiment results.

In [68]:
print("=" * 65)
print("EXPERIMENT 1 – TOKENIZATION, STEMMING AND LEMMATIZATION")
print("=" * 65)

print("\nTOKENIZATION")
print("Whitespace tokens              :", len(whitespace_tokens))
print("spaCy tokens                   :", len(spacy_tokens))
print("Filtered spaCy tokens         :", len(clean_tokens))

print("\nVOCABULARY")
for _, row in variation_metrics.iterrows():
    print(
        f"{row['Method']:25} | "
        f"Total = {row['Total Words']:2} | "
        f"Unique = {row['Unique Forms']:2} | "
        f"Reduction = {row['Reduction %']:.2f}%"
        if isinstance(row["Reduction %"], (int, float))
        else
        f"{row['Method']:25} | Total = {row['Total Words']:2} | Unique = {row['Unique Forms']:2}"
    )

=================================================================
EXPERIMENT 1 – TOKENIZATION, STEMMING AND LEMMATIZATION
=================================================================

TOKENIZATION
Whitespace tokens              : 51
spaCy tokens                   : 64
Filtered spaCy tokens         : 51

VOCABULARY
Original words            | Total = 51 | Unique = 43 | Reduction = 0.00%
Porter stemming           | Total = 51 | Unique = 41 | Reduction = 4.65%
Snowball stemming         | Total = 51 | Unique = 41 | Reduction = 4.65%
spaCy lemmatization       | Total = 51 | Unique = 40 | Reduction = 6.98%